const Q=[
['Concepts & Models','What is a large language model?',['A database that only retrieves stored answers','A model trained to predict and generate language from patterns in data','A browser extension','A file that stores passwords'],1],
['Concepts & Models','What is a context window?',['The input and conversation a model can consider at one time','The browser window containing a chat','The number of account users','The time before a chat expires'],0],
['Concepts & Models','What is a token?',['Exactly one word','A chunk of text a model reads or writes','An account password','A truth score'],1],
['Concepts & Models','Which description of OpenClaw is most accurate?',['A photo editor','An open-source agent system connecting models to tools, files, and channels','Claude web search','An image benchmark'],1],
['Concepts & Models','What does SOUL.md do in an OpenClaw workspace?',['Stores API keys','Sets persona, tone, and boundaries','Counts tokens','Creates a container'],1],
['Judgment & Safety','What is a sandbox in an agent workflow?',['A public prompt room','An isolated environment limiting what code or tools can reach','An old-chat archive','A model without internet'],1],
['Applied Workflows','You need a polished one-page announcement from notes. What is the simplest suitable setup?',['A normal chat with context and constraints','A permanent autonomous agent','A five-agent team','No AI'],0],
['Applied Workflows','Every Monday, AI should read sales reports, calculate changes, draft a summary, and save it for review. Best fit?',['A fresh chat with no tools','One scheduled agent with file access and approval','Ten specialist agents','No AI'],1],
['Applied Workflows','You need parallel research on five markets, separate analyses, synthesis, and fact-checking. Best fit?',['One short prompt','One agent doing everything sequentially','A coordinated specialist team with a reviewer','No AI'],2],
['Applied Workflows','What chiefly distinguishes an agent from a chatbot?',['Agents are always smarter','An agent can pursue a goal over steps and use tools','Agents never need review','Agents cost nothing'],1],
['Applied Workflows','Before building multiple agents, what should you ask first?',['Which model has the coolest name?','Can one chat or one agent do this reliably?','How many agents can I deploy?','Can I remove humans entirely?'],1],
['Judgment & Safety','An AI gives a confident statistic with a citation. What should you do?',['Trust the citation','Verify the source and exact claim','Use it if wording sounds formal','Ask the same AI if it is sure'],1],
['Judgment & Safety','What should you avoid pasting into a consumer AI chat without confirmed controls and permission?',['A public press release','A website description','Customer records, passwords, confidential contracts, or health data','Public holidays'],2],
['Judgment & Safety','How do you know an AI workflow is useful?',['Count tools','Measure time, cost, errors, and quality against the old process','Choose the biggest context window','Ask AI to grade itself'],1],
['Judgment & Safety','Which task should remain human-led even when AI assists?',['Headline options','Public-note summaries','Final medical, legal, hiring, or irreversible financial decisions','Spreadsheet formatting'],2]
];
const cats={'Concepts & Models':[0,0],'Applied Workflows':[0,0],'Judgment & Safety':[0,0]},letters=['A','B','C','D'];let i=0,a=Array(Q.length).fill(null);const $=id=>document.getElementById(id);function show(id){['intro','quiz','results'].forEach(x=>$(x).classList.toggle('hidden',x!==id));scrollTo(0,0)}function render(){let x=Q[i];$('cat').textContent=x[0];$('count').textContent=`${i+1} / ${Q.length}`;$('bar').style.width=`${(i+1)/Q.length*100}%`;$('q').textContent=x[1];$('opts').innerHTML=x[2].map((o,j)=>`<button class="quiz-option ${a[i]===j?'selected':''}" data-i="${j}"><span class="option-letter">${letters[j]}</span><span>${o}</span></button>`).join('');document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>{a[i]=+b.dataset.i;render()});$('back').disabled=i===0;$('next').disabled=a[i]===null;$('next').textContent=i===Q.length-1?'See my result →':'Next →'}
$('start').onclick=()=>{show('quiz');render()};$('back').onclick=()=>{if(i){i--;render()}};$('next').onclick=()=>{if(a[i]===null)return;if(i<Q.length-1){i++;render();scrollTo(0,0)}else result()};
const levels={Beginner:{icon:'🌱',head:'You can begin using AI productively now—without mastering everything first.',copy:'Your score shows gaps in the concepts and judgment that make AI dependable. Your fastest path is learning the basics and building one useful, repeatable workflow.',steps:['Learn tokens, context windows, tools, sandboxes, chats, and agents.','Choose one weekly task and improve it for four weeks.','Verify claims, protect sensitive data, and edit important outputs.']},Intermediate:{icon:'⚙️',head:'You already get value from AI. Now make it reliable.',copy:'You understand the basics. The next leap is turning isolated good chats into documented workflows with tools, permissions, checks, and measurements.',steps:['Document your best prompt or process.','Automate one bounded workflow with an approval gate.','Measure time, quality, and errors before and after AI.']},Advanced:{icon:'🧭',head:'You understand the systems. Your advantage now comes from discipline.',copy:'You can reason about models, context, agents, tools, safety, and workflow design. Avoid over-engineering: build the smallest system that works and add autonomy only when evidence justifies it.',steps:['Run evaluations on representative tasks.','Separate read, write, publish, and irreversible permissions.','Teach or publish the frameworks that work.']}};
function result(){Object.keys(cats).forEach(k=>cats[k]=[0,0]);let total=0;Q.forEach((x,n)=>{let s=a[n]===x[3]?2:0;total+=s;cats[x[0]][0]+=s;cats[x[0]][1]+=2});let name=total<=14?'Beginner':total<=23?'Intermediate':'Advanced',d=levels[name];$('icon').textContent=d.icon;$('level').textContent=name;$('score').textContent=`Score: ${total} / 30`;$('headline').textContent=d.head;$('copy').textContent=d.copy;let weak=Object.entries(cats).sort((x,y)=>x[1][0]/x[1][1]-y[1][0]/y[1][1])[0];$('weak').innerHTML=`<strong>Your first priority: ${weak[0]}</strong><br>Improving your weakest area usually creates more value than adding another AI subscription.`;$('breakdown').innerHTML=Object.entries(cats).map(([k,v])=>`<div class="score-row"><div class="score-label">${k}</div><div class="score-bar"><span style="width:${v[0]/v[1]*100}%"></span></div><div class="score-value">${v[0]}/${v[1]}</div></div>`).join('');$('steps').innerHTML=d.steps.map(x=>`<li style="margin-bottom:12px">${x}</li>`).join('');$('rec').innerHTML=name==='Beginner'?`<span class="chip">Recommended for your level</span><h3>Join the AI Foundations course waitlist.</h3><p>Short faceless video lessons, practical exercises, and one workflow you can use immediately.</p><form class="waitlist-form" action="https://formspree.io/f/mvzynwra" method="POST"><input type="hidden" name="source" value="quiz-beginner"><div class="form-row"><input class="field" type="email" name="email" placeholder="you@example.com" required><button class="btn-dark">Join waitlist</button></div><p class="form-note">The course is not yet for sale.</p></form>`:name==='Intermediate'?`<span class="chip">Recommended</span><h3>Route one real task before automating it.</h3><p>Find out whether it needs a chat, one agent, a team, or none.</p><a class="btn-dark" href="simulator.html">Open Task Router</a>`:`<span class="chip">Recommended</span><h3>Use the agent guide as a design check.</h3><p>Choose the smallest dependable architecture.</p><a class="btn-dark" href="blog/chat-agent-or-agent-team.html">Read guide</a>`;show('results');if(typeof gtag==='function')gtag('event','quiz_complete',{ai_fluency_level:name,score:total})}
$('retake').onclick=()=>{i=0;a=Array(Q.length).fill(null);show('intro')};